### PR TITLE
Update Bootstrap and Bootswatch to 3.3.2

### PR DESCRIPTION
**Pull request by PrplHaz4**

### CODE REVIEW

**Comment by rickparrish** [comment]
Awesome, thanks for updating.

**Comment by PrplHaz4** [comment]
@rickparrish sure thing!  I probably missed some stuff - would prob be a good idea to include a decent test page "template" in the package to check for consistency...

**Comment by rickparrish** [comment]
The bootswatch.php page template can be used for that purpose.  Although I guess it should probably be updated with every new update as well, so something looking incorrect on that page doesn't necessarily mean bootstrap was updated incorrectly, it may just mean the test page needs to be updated as well.

**Comment by PrplHaz4** [comment]
@rickparrish That is exactly what I was looking for actually - don't know why/how I missed it, but remember it being there at some point....

**Pull request merged**
